### ISSUE TITLE
Dialog

### ISSUE THREAD

**Issue by ritu99** [DASAR/ShiftColorPicker#3]
In a dialog fragment the color picker isn't visible. In a separate fragment however it works fine.

![image](https://cloud.githubusercontent.com/assets/5049197/8763489/b7ef4e10-2d63-11e5-884d-a2a6db186864.png)

**Comment by DASAR-zz** [comment]
I will check it.

**Comment by paulcanning** [comment]
Any update on this? I'd also like to use the color picker in a custom dialog.

**Comment by DASAR-zz** [comment]
@paulcanning you can find working example in repository pull requests. It's implemented but not yet merged with master.

**Comment by DASAR-zz** [comment]
Now repository contains working dialog sample.
