### ISSUE TITLE
Cannot add in Android Studio

### ISSUE THREAD

**Issue by paulcanning** [DASAR/ShiftColorPicker#5]
I have added the maven repo, then added the compile command to the apps build.gradle file, in dependencies.

The gradle build failed, saying it failed to find uz.shift:colorpicker:0.5

Is there anything specific need for Android Studio?

**Comment by DASAR-zz** [comment]
``` gradle
repositories {
     maven {
        url  "http://dl.bintray.com/dasar/maven"
     }
}

compile(group: 'uz.shift', name: 'colorpicker', version: '0.5', ext: 'aar')
```

Repositories must be added outside of any parent containers. There is nothing special.
Make sure your compile directive exactly like above.

**Comment by paulcanning** [comment]
Well I did that but it didn't work, like I said.  I ended up added it as a packaged library.

**Comment by DASAR-zz** [comment]
@paulcanning I merged sample with dialog in master branch and now this sample will use Bintray repo as example for you and others. Please see gradle files for 'sample2' module.

**Comment by DASAR-zz** [comment]
@paulcanning Repository updated with dialog example which configured to use library from Bintray  repository.

**Comment by DASAR-zz** [comment]
@paulcanning please try to add it using example in sample2 module and let me know how it going. I was tested it myself, works as expected.

**Comment by paulcanning** [comment]
It now imports correctly, thank you.

**Comment by DASAR-zz** [comment]
Fixed
